Update MANIFEST.in
Add the v1 schema to the manifest because:

> FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.6/site-packages/vdom/schemas/vdom_schema_v1.json'